server:
  port: 8084

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/quizdb
  datasource:
    url: jdbc:postgresql://localhost:5432/quizwhiz
    username: alvoro
    password: securekotik25
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-bean-definition-overriding: true

jwt:
  secret: 'n4uB0oP1mQ6sT8yZ0xR3vL7eF2aD5jK9sU8iE4wQ1zC3bN6rT8vY0pL7kJ2dS9aF'
  expiration: 3600000
