server:
  port: 8082

auth:
  service:
    url: http://127.0.0.1:8081
quizservice:
  url: 127.0.0.1:8083

logging:
  level:
    org.springframework.security: DEBUG
jwt:
  secret: 'n4uB0oP1mQ6sT8yZ0xR3vL7eF2aD5jK9sU8iE4wQ1zC3bN6rT8vY0pL7kJ2dS9aF'
  expiration: 3600000